<div class="col-md-8 modal__wrapper">
   <div class="modal__body">
  <?php if($block->isLoggedIn()): ?>
      <div class="modal-body__header">
          <p>
            <button class="modal-body__header-btn-form hide-modal" type="submit"><span class="visually-hidden"><?= $block->escapeHtmlAttr(__('Close')) ?><span></button>
          </p>
      </div>
       <form name="addData" method="post" id="form_id" class="form-review"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <div class="control">
                                <textarea name="review" id="review" title="Review" value="" class="input-text"
                                          rows="10" cols="100" type="text" data-validate="{required:true}"></textarea>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar-review">
                <div class="primary">
                    <button type="submit" class="action submit primary review" title="Submit"><span><?= $block->
                        escapeHtmlAttr(__('Submit')) ?></span></button>
                </div>
            </div>
        </form>
    <?php else: ?>
      <div class="modal-body__header">
          <p>
            <button class="modal-body__header-btn-message hide-modal" type="submit"><span class="visually-hidden"><?= $block->escapeHtmlAttr(__('Close')) ?><span></button>
          </p>
      </div>
      <div class="modal-body__footer"><span><?php echo __('In order to leave a review, you need to register on the site or log in.'); ?></span></div>
    <?php endif ?>
   </div>
</div>
<script type="text/x-magento-init">
   {
       "#form_id": {
           "formAjax": {
           				       "url": "<?php echo $this->getUrl('*/*/index'); ?>",
                         "action": "<?php echo $this->getFormAction(); ?>"
           			       }
       },

       ".hide-modal": {
            "hideModal" : {
                            "event": "click",
                            "action": "<?php echo $this->getFormAction(); ?>"
                          }
        }
   }
</script>