<div class="col-md-8">
	<?php if($block->isLoggedIn()): ?>
       <form name="addData" method="post" id="form_id" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Review')) ?></span></label>
                            <div class="control">
                                <textarea name="review" id="review" title="Review" value="" class="input-text"
                                      	  rows="10" cols="45" type="text" data-validate="{required:true}"></textarea>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Submit"><span><?= $block->
                        escapeHtmlAttr(__('Submit')) ?></span></button>
                </div>
            </div>
        </form>
    <?php else: ?>
      <div class="message info empty"><span><?php echo __('In order to leave a review, you need to register on the site or log in.'); ?></span></div>
    <?php endif ?>
</div>
<script type="text/x-magento-init">
   {
       "#form_id": {
           "formAjax": { "id": "<?php echo $block->getCustomerId(); ?>",
           				       "url": "<?php echo $this->getUrl('*/*/index'); ?>"
           			      }
       }
   }
</script>