<?php

?>
<div class="content-banner">
	<div class="content-banner__item1">
		<a class="content-banner__link" href="#">
			<img class="content-banner__image" src='<?php echo $this->getViewFileUrl('images/banners/look-book.jpg'); ?>' alt="image" />
		</a>
	</div>
	<div class="content-banner__wrapper-one">
		<div class="content-banner__item2">
			<a class="content-banner__link" href="#">
				<img class="content-banner__image" src='<?php echo $this->getViewFileUrl('images/banners/complete-your-style.jpg'); ?>' alt="image" />
			</a>
		</div>
		<div class="content-banner__wrapper-two">
			<div class="content-banner__item3">
				<img class="content-banner__image" src='<?php echo $this->getViewFileUrl('images/banners/show-your-love-this-mothers-day.jpg'); ?>' alt="image" />
			</div>
			<div class="content-banner__wrapper-three">
				<div class="content-banner__item4">
					<img class="content-banner__image" src='<?php echo $this->getViewFileUrl('images/banners/scale-off-storewide.jpg'); ?>' alt="image" />
				</div>
				<div class="content-banner__item5">
					<img class="content-banner__image" src='<?php echo $this->getViewFileUrl('images/banners/free-shipping.jpg'); ?>' alt="image" />
				</div>
			</div>
		</div>
	</div>
</div>
