<?php
$product_collection = $this->getBestsellerProduct(); //$this->getCategoryCollection(); 
?>
<?php if ($product_collection):?>
<div class="block widget block-bestseller-products grid">
    <div class="block-title">
        <h1>Hot Sellers</h1>
        <p>Here is what`s trending on Luma right now</p>
    </div>
    <div class="block-content">
        <div class="products-grid grid arrows">
            <ol class="product-items slider-product-items">
                <?php $iterator = 1; ?>
                <?php foreach ($product_collection as $item):
                    $_product =$block->getProduct($item->getProductId());
                    ?>
 
                    <?php echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                    <div class="product-item-info slider-product-item-info">
                        <?php
                            $image_url = $block->imageHelperObj()
                                               ->init($_product, 'product_page_image_small')
                                               ->setImageFile($_product->getFile())
                                               ->constrainOnly(true)
                                               ->keepAspectRatio(true)
                                               ->keepTransparency(true)
                                               ->keepFrame(false)
                                               ->resize(300, 524)
                                               ->getUrl();
                        ?>
                        <a href="<?php  echo $_product->getProductUrl() ?>" class="product-item-photo">
                            <img src="<?php echo  $image_url;?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
                        </a>
                        <div class="product-item-details">
                            <strong class="product-item-name slider-product-item-name">
                                <a title="<?php echo $block->escapeHtml($_product->getName()) ?>"
                                href="<?php echo $_product->getProductUrl() ?>"
                                class="product-item-link slider-product-item-link">
                                    <?php echo $block->escapeHtml($_product->getName()) ?>
                                </a>
                            </strong>
                            <?php
                            echo $this->getProductPriceHtml($_product);
                            ?>
                            <div class="product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                            <button class="action tocart primary slider-action-tocart"
                                                    data-mage-init='{"redirectUrl":{"url":"<?php  echo $block->getAddToCartUrl($_product) ?>"}}'
                                                    type="button" title="<?php echo __('Add to Cart') ?>">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getId()]);
                                            ?>
                                            <button class="action tocart primary slider-action-tocart"
                                                    data-post='<?php echo $postData; ?>'
                                                    type="button" title="<?php echo __('Add to Cart') ?>">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div class="actions-secondary">
                                    <a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><span>
                                        <?php $block->escapeHtml(__('Add to Wish List'))  ?></span></a>
                                    <a class="action tocompare" href="<?php $block->escapeUrl($block->getAddToCompareUrl($_product)) ?>"><span> </span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php echo($iterator == count($product_collection)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
        <?php endif;?>